# Lab 3

## Data Preprocessing

**Step 1 - Import Libraries**

In [2]:
%pip install tensorflow
import numpy as np
import pandas as pd
import tensorflow as tf

   ---------------------------------------- 0.0/331.9 MB ? eta -:--:--
   ---------------------------------------- 1.6/331.9 MB 9.3 MB/s eta 0:00:36
   ---------------------------------------- 2.4/331.9 MB 7.9 MB/s eta 0:00:42
    --------------------------------------- 4.5/331.9 MB 8.1 MB/s eta 0:00:41
    --------------------------------------- 5.8/331.9 MB 7.5 MB/s eta 0:00:44
    --------------------------------------- 7.3/331.9 MB 7.5 MB/s eta 0:00:44
   - -------------------------------------- 8.9/331.9 MB 7.3 MB/s eta 0:00:45
   - -------------------------------------- 10.2/331.9 MB 7.2 MB/s eta 0:00:45
   - -------------------------------------- 11.8/331.9 MB 7.2 MB/s eta 0:00:45
   - -------------------------------------- 13.1/331.9 MB 7.1 MB/s eta 0:00:45
   - -------------------------------------- 14.7/331.9 MB 7.1 MB/s eta 0:00:45
   - -------------------------------------- 15.7/331.9 MB 6.9 MB/s eta 0:00:46
   - -------------------------------------- 16.5/331.9 MB 6.8 MB/s

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.37.1 requires protobuf<6,>=3.20, but you have protobuf 6.33.1 which is incompatible.


**Step 2 - Load Data**

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

Inspect data (X)

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


**Step 3 - Encode Categorical Data**

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

Check data (X) with print. The result,

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


**Step 4 - Encode the "Geography" Column with One Hot Encoder**

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

Check data (X) with print. The result,

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


**Step 5 - Split Data**

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

**Step 6 - Feature Scaling**

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Constructing the ANN Model

**Step 1 - Initialize the ANN Model**

In [14]:
ann = tf.keras.models.Sequential()

**Step 2 - Create the Input Layer and the First Hidden Layer**

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Step 3 - Create the Second Hidden Layer**

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Step 4 - Create the Output Layer**

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the Model

**Step 1 - Compile the ANN Model (Unify the Architecture)**

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**Step 2 - Fit the Model**

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7390 - loss: 0.5675
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7959 - loss: 0.4706
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7959 - loss: 0.4511
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7952 - loss: 0.4394
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7959 - loss: 0.4314
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8033 - loss: 0.4252
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8135 - loss: 0.4190
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8191 - loss: 0.4128
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8221 - loss: 0.4056
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8263 - loss: 0.3991
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8298 - loss: 0.3933
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## Making Predictions

Given the following information,

- Geography: France

- Credit Score: 600

- Gender: Male

- Age: 40 years old

- Tenure: 3 years

- Balance: $ 60000

- Number of Products: 2

- Does this customer have a credit card? Yes

- Is this customer an Active Member: Yes

- Estimated Salary: $ 50000

Should this customer be retained?

**Model the New Data and Make a Prediction**

In [25]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
[[False]]


Is the result **False**?

Yes, the result is False. That means the ANN predicts this customer will not leave. So the customer should be retained (because they are not at risk).

**Predictions with the Testing Data**

In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Evaluate Accuracy and the Confusion Matrix**

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1511   84]
 [ 194  211]]


0.861